/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedWebsitesRouteImport } from './routes/_protected/_websites'
import { Route as ProtectedClientsRouteImport } from './routes/_protected/_clients'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ProtectedClientsClientsIndexRouteImport } from './routes/_protected/_clients/clients.index'
import { Route as ProtectedWebsitesWebsitesNewRouteImport } from './routes/_protected/_websites/websites.new'
import { Route as ProtectedWebsitesWebsitesImportRouteImport } from './routes/_protected/_websites/websites.import'
import { Route as ProtectedWebsitesWebsitesWebsiteIdRouteImport } from './routes/_protected/_websites/websites.$websiteId'
import { Route as ProtectedClientsClientsNewRouteImport } from './routes/_protected/_clients/clients.new'
import { Route as ProtectedClientsClientsClientIdRouteImport } from './routes/_protected/_clients/clients.$clientId'
import { Route as ProtectedWebsitesWebsitesWebsiteIdEditRouteImport } from './routes/_protected/_websites/websites.$websiteId.edit'
import { Route as ProtectedClientsClientsClientIdEditRouteImport } from './routes/_protected/_clients/clients.$clientId.edit'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedWebsitesRoute = ProtectedWebsitesRouteImport.update({
  id: '/_websites',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedClientsRoute = ProtectedClientsRouteImport.update({
  id: '/_clients',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedClientsClientsIndexRoute =
  ProtectedClientsClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => ProtectedClientsRoute,
  } as any)
const ProtectedWebsitesWebsitesNewRoute =
  ProtectedWebsitesWebsitesNewRouteImport.update({
    id: '/websites/new',
    path: '/websites/new',
    getParentRoute: () => ProtectedWebsitesRoute,
  } as any)
const ProtectedWebsitesWebsitesImportRoute =
  ProtectedWebsitesWebsitesImportRouteImport.update({
    id: '/websites/import',
    path: '/websites/import',
    getParentRoute: () => ProtectedWebsitesRoute,
  } as any)
const ProtectedWebsitesWebsitesWebsiteIdRoute =
  ProtectedWebsitesWebsitesWebsiteIdRouteImport.update({
    id: '/websites/$websiteId',
    path: '/websites/$websiteId',
    getParentRoute: () => ProtectedWebsitesRoute,
  } as any)
const ProtectedClientsClientsNewRoute =
  ProtectedClientsClientsNewRouteImport.update({
    id: '/clients/new',
    path: '/clients/new',
    getParentRoute: () => ProtectedClientsRoute,
  } as any)
const ProtectedClientsClientsClientIdRoute =
  ProtectedClientsClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => ProtectedClientsRoute,
  } as any)
const ProtectedWebsitesWebsitesWebsiteIdEditRoute =
  ProtectedWebsitesWebsitesWebsiteIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => ProtectedWebsitesWebsitesWebsiteIdRoute,
  } as any)
const ProtectedClientsClientsClientIdEditRoute =
  ProtectedClientsClientsClientIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => ProtectedClientsClientsClientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof AuthLoginRoute
  '/settings': typeof ProtectedSettingsRoute
  '/clients/$clientId': typeof ProtectedClientsClientsClientIdRouteWithChildren
  '/clients/new': typeof ProtectedClientsClientsNewRoute
  '/websites/$websiteId': typeof ProtectedWebsitesWebsitesWebsiteIdRouteWithChildren
  '/websites/import': typeof ProtectedWebsitesWebsitesImportRoute
  '/websites/new': typeof ProtectedWebsitesWebsitesNewRoute
  '/clients/': typeof ProtectedClientsClientsIndexRoute
  '/clients/$clientId/edit': typeof ProtectedClientsClientsClientIdEditRoute
  '/websites/$websiteId/edit': typeof ProtectedWebsitesWebsitesWebsiteIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/login': typeof AuthLoginRoute
  '/settings': typeof ProtectedSettingsRoute
  '/clients/$clientId': typeof ProtectedClientsClientsClientIdRouteWithChildren
  '/clients/new': typeof ProtectedClientsClientsNewRoute
  '/websites/$websiteId': typeof ProtectedWebsitesWebsitesWebsiteIdRouteWithChildren
  '/websites/import': typeof ProtectedWebsitesWebsitesImportRoute
  '/websites/new': typeof ProtectedWebsitesWebsitesNewRoute
  '/clients': typeof ProtectedClientsClientsIndexRoute
  '/clients/$clientId/edit': typeof ProtectedClientsClientsClientIdEditRoute
  '/websites/$websiteId/edit': typeof ProtectedWebsitesWebsitesWebsiteIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_protected/_clients': typeof ProtectedClientsRouteWithChildren
  '/_protected/_websites': typeof ProtectedWebsitesRouteWithChildren
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/_clients/clients/$clientId': typeof ProtectedClientsClientsClientIdRouteWithChildren
  '/_protected/_clients/clients/new': typeof ProtectedClientsClientsNewRoute
  '/_protected/_websites/websites/$websiteId': typeof ProtectedWebsitesWebsitesWebsiteIdRouteWithChildren
  '/_protected/_websites/websites/import': typeof ProtectedWebsitesWebsitesImportRoute
  '/_protected/_websites/websites/new': typeof ProtectedWebsitesWebsitesNewRoute
  '/_protected/_clients/clients/': typeof ProtectedClientsClientsIndexRoute
  '/_protected/_clients/clients/$clientId/edit': typeof ProtectedClientsClientsClientIdEditRoute
  '/_protected/_websites/websites/$websiteId/edit': typeof ProtectedWebsitesWebsitesWebsiteIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/clients/$clientId'
    | '/clients/new'
    | '/websites/$websiteId'
    | '/websites/import'
    | '/websites/new'
    | '/clients/'
    | '/clients/$clientId/edit'
    | '/websites/$websiteId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/clients/$clientId'
    | '/clients/new'
    | '/websites/$websiteId'
    | '/websites/import'
    | '/websites/new'
    | '/clients'
    | '/clients/$clientId/edit'
    | '/websites/$websiteId/edit'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_auth/login'
    | '/_protected/_clients'
    | '/_protected/_websites'
    | '/_protected/settings'
    | '/_protected/'
    | '/_protected/_clients/clients/$clientId'
    | '/_protected/_clients/clients/new'
    | '/_protected/_websites/websites/$websiteId'
    | '/_protected/_websites/websites/import'
    | '/_protected/_websites/websites/new'
    | '/_protected/_clients/clients/'
    | '/_protected/_clients/clients/$clientId/edit'
    | '/_protected/_websites/websites/$websiteId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_websites': {
      id: '/_protected/_websites'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedWebsitesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_clients': {
      id: '/_protected/_clients'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedClientsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/_clients/clients/': {
      id: '/_protected/_clients/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ProtectedClientsClientsIndexRouteImport
      parentRoute: typeof ProtectedClientsRoute
    }
    '/_protected/_websites/websites/new': {
      id: '/_protected/_websites/websites/new'
      path: '/websites/new'
      fullPath: '/websites/new'
      preLoaderRoute: typeof ProtectedWebsitesWebsitesNewRouteImport
      parentRoute: typeof ProtectedWebsitesRoute
    }
    '/_protected/_websites/websites/import': {
      id: '/_protected/_websites/websites/import'
      path: '/websites/import'
      fullPath: '/websites/import'
      preLoaderRoute: typeof ProtectedWebsitesWebsitesImportRouteImport
      parentRoute: typeof ProtectedWebsitesRoute
    }
    '/_protected/_websites/websites/$websiteId': {
      id: '/_protected/_websites/websites/$websiteId'
      path: '/websites/$websiteId'
      fullPath: '/websites/$websiteId'
      preLoaderRoute: typeof ProtectedWebsitesWebsitesWebsiteIdRouteImport
      parentRoute: typeof ProtectedWebsitesRoute
    }
    '/_protected/_clients/clients/new': {
      id: '/_protected/_clients/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ProtectedClientsClientsNewRouteImport
      parentRoute: typeof ProtectedClientsRoute
    }
    '/_protected/_clients/clients/$clientId': {
      id: '/_protected/_clients/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ProtectedClientsClientsClientIdRouteImport
      parentRoute: typeof ProtectedClientsRoute
    }
    '/_protected/_websites/websites/$websiteId/edit': {
      id: '/_protected/_websites/websites/$websiteId/edit'
      path: '/edit'
      fullPath: '/websites/$websiteId/edit'
      preLoaderRoute: typeof ProtectedWebsitesWebsitesWebsiteIdEditRouteImport
      parentRoute: typeof ProtectedWebsitesWebsitesWebsiteIdRoute
    }
    '/_protected/_clients/clients/$clientId/edit': {
      id: '/_protected/_clients/clients/$clientId/edit'
      path: '/edit'
      fullPath: '/clients/$clientId/edit'
      preLoaderRoute: typeof ProtectedClientsClientsClientIdEditRouteImport
      parentRoute: typeof ProtectedClientsClientsClientIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedClientsClientsClientIdRouteChildren {
  ProtectedClientsClientsClientIdEditRoute: typeof ProtectedClientsClientsClientIdEditRoute
}

const ProtectedClientsClientsClientIdRouteChildren: ProtectedClientsClientsClientIdRouteChildren =
  {
    ProtectedClientsClientsClientIdEditRoute:
      ProtectedClientsClientsClientIdEditRoute,
  }

const ProtectedClientsClientsClientIdRouteWithChildren =
  ProtectedClientsClientsClientIdRoute._addFileChildren(
    ProtectedClientsClientsClientIdRouteChildren,
  )

interface ProtectedClientsRouteChildren {
  ProtectedClientsClientsClientIdRoute: typeof ProtectedClientsClientsClientIdRouteWithChildren
  ProtectedClientsClientsNewRoute: typeof ProtectedClientsClientsNewRoute
  ProtectedClientsClientsIndexRoute: typeof ProtectedClientsClientsIndexRoute
}

const ProtectedClientsRouteChildren: ProtectedClientsRouteChildren = {
  ProtectedClientsClientsClientIdRoute:
    ProtectedClientsClientsClientIdRouteWithChildren,
  ProtectedClientsClientsNewRoute: ProtectedClientsClientsNewRoute,
  ProtectedClientsClientsIndexRoute: ProtectedClientsClientsIndexRoute,
}

const ProtectedClientsRouteWithChildren =
  ProtectedClientsRoute._addFileChildren(ProtectedClientsRouteChildren)

interface ProtectedWebsitesWebsitesWebsiteIdRouteChildren {
  ProtectedWebsitesWebsitesWebsiteIdEditRoute: typeof ProtectedWebsitesWebsitesWebsiteIdEditRoute
}

const ProtectedWebsitesWebsitesWebsiteIdRouteChildren: ProtectedWebsitesWebsitesWebsiteIdRouteChildren =
  {
    ProtectedWebsitesWebsitesWebsiteIdEditRoute:
      ProtectedWebsitesWebsitesWebsiteIdEditRoute,
  }

const ProtectedWebsitesWebsitesWebsiteIdRouteWithChildren =
  ProtectedWebsitesWebsitesWebsiteIdRoute._addFileChildren(
    ProtectedWebsitesWebsitesWebsiteIdRouteChildren,
  )

interface ProtectedWebsitesRouteChildren {
  ProtectedWebsitesWebsitesWebsiteIdRoute: typeof ProtectedWebsitesWebsitesWebsiteIdRouteWithChildren
  ProtectedWebsitesWebsitesImportRoute: typeof ProtectedWebsitesWebsitesImportRoute
  ProtectedWebsitesWebsitesNewRoute: typeof ProtectedWebsitesWebsitesNewRoute
}

const ProtectedWebsitesRouteChildren: ProtectedWebsitesRouteChildren = {
  ProtectedWebsitesWebsitesWebsiteIdRoute:
    ProtectedWebsitesWebsitesWebsiteIdRouteWithChildren,
  ProtectedWebsitesWebsitesImportRoute: ProtectedWebsitesWebsitesImportRoute,
  ProtectedWebsitesWebsitesNewRoute: ProtectedWebsitesWebsitesNewRoute,
}

const ProtectedWebsitesRouteWithChildren =
  ProtectedWebsitesRoute._addFileChildren(ProtectedWebsitesRouteChildren)

interface ProtectedRouteChildren {
  ProtectedClientsRoute: typeof ProtectedClientsRouteWithChildren
  ProtectedWebsitesRoute: typeof ProtectedWebsitesRouteWithChildren
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedClientsRoute: ProtectedClientsRouteWithChildren,
  ProtectedWebsitesRoute: ProtectedWebsitesRouteWithChildren,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
